on:
  workflow_dispatch:
    inputs:
      version:
        description: new app version x.x.x.

jobs:
  versionup:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: yanamura/ios-bump-version@v1.7.0
      with:
        version: '1.1.0'
        build-number: '10'
- name: update
  run: |
    git add .
    git commit -m "bump version"
    git push origin HEAD
