name: increase bulidnumber automatically

on:
  push

jobs:
  versionup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: yanamura/ios-bump-version@v1
        with:
          version: 1.1.0 #1234
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD
